%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-domain-coordinator
Version:        0.15.6
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS domain_coordinator package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-rolling-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-rolling-ament-copyright
BuildRequires:  ros-rolling-ament-flake8
BuildRequires:  ros-rolling-ament-pep257
BuildRequires:  ros-rolling-ament-xmllint
%endif

%description
A tool to coordinate unique ROS_DOMAIN_IDs across multiple processes

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/rolling"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Tue Dec 09 2025 Brandon Ong <brandon@openrobotics.org> - 0.15.6-1
- Autogenerated by Bloom

* Fri Nov 28 2025 Brandon Ong <brandon@openrobotics.org> - 0.15.5-1
- Autogenerated by Bloom

* Fri Oct 31 2025 Brandon Ong <brandon@openrobotics.org> - 0.15.4-1
- Autogenerated by Bloom

* Fri Oct 17 2025 Brandon Ong <brandon@openrobotics.org> - 0.15.3-1
- Autogenerated by Bloom

* Tue Jul 29 2025 Brandon Ong <brandon@openrobotics.org> - 0.15.2-1
- Autogenerated by Bloom

* Mon Jun 30 2025 Brandon Ong <brandon@openrobotics.org> - 0.15.1-1
- Autogenerated by Bloom

* Thu Apr 24 2025 Brandon Ong <brandon@openrobotics.org> - 0.15.0-1
- Autogenerated by Bloom

* Fri Apr 18 2025 Brandon Ong <brandon@openrobotics.org> - 0.14.3-1
- Autogenerated by Bloom

* Fri Apr 18 2025 Brandon Ong <brandon@openrobotics.org> - 0.14.2-1
- Autogenerated by Bloom

* Wed Apr 02 2025 Brandon Ong <brandon@openrobotics.org> - 0.14.1-1
- Autogenerated by Bloom

* Wed Mar 19 2025 Brandon Ong <brandon@openrobotics.org> - 0.14.0-1
- Autogenerated by Bloom

* Wed Nov 20 2024 Brandon Ong <brandon@openrobotics.org> - 0.13.1-1
- Autogenerated by Bloom

* Fri Apr 26 2024 Brandon Ong <brandon@openrobotics.org> - 0.13.0-1
- Autogenerated by Bloom

* Tue Mar 05 2024 Brandon Ong <brandon@openrobotics.org> - 0.12.0-2
- Autogenerated by Bloom

